Repository GravitLauncher/Launcher, pull requests merged in 2018-11, with the labels that each got.

#49 ThreadCount #48
  LaunchServer/src/main/java/ru/gravit/launchserver/LaunchServer.java
  LaunchServer/src/main/java/ru/gravit/launchserver/socket/NettyServerSocketHandler.java
  LaunchServer/src/main/java/ru/gravit/launchserver/socket/ServerSocketHandler.java
  LaunchServer/src/main/java/ru/gravit/launchserver/socket/websocket/WebSocketService.java
  LaunchServer/src/main/java/ru/gravit/launchserver/socket/websocket/json/auth/CheckServerResponse.java
  LauncherAPI/src/main/java/ru/gravit/launcher/request/websockets/ClientWebSocketService.java
  ServerWrapper/src/main/java/ru/gravit/launcher/server/ServerAgent.java
  ServerWrapper/src/main/java/ru/gravit/launcher/server/ServerWrapper.java
  libLauncher/src/main/java/ru/gravit/launcher/hasher/HashedDir.java
  libLauncher/src/main/java/ru/gravit/launcher/hasher/HashedEntryAdapter.java
  libLauncher/src/main/java/ru/gravit/launcher/ssl/LauncherSSLContext.java
  libLauncher/src/main/java/ru/gravit/utils/helper/JVMHelper.java
Labels: optimization

#53 Fix patch.
  compat/BungeeCord.patch
  compat/LaunchWrapper.patch
Labels: bug

#43 Runtime fixes and improvements.
  Launcher/runtime/dialog/login.fxml
  Launcher/runtime/dialog/offline/describe.html
  Launcher/runtime/dialog/overlay/debug/debug.fxml
  Launcher/runtime/dialog/overlay/update/update.fxml
  Launcher/runtime/engine/api.js
  Launcher/src/main/java/ru/gravit/launcher/LauncherEngine.java
  Launcher/src/main/java/ru/gravit/launcher/gui/choosebox/CheckBitSetModelBase.java
  Launcher/src/main/java/ru/gravit/launcher/gui/choosebox/CheckComboBox.java
  Launcher/src/main/java/ru/gravit/launcher/gui/choosebox/CheckComboBoxSkin.java
  Launcher/src/main/java/ru/gravit/launcher/gui/choosebox/ControlsFXControl.java
  Launcher/src/main/java/ru/gravit/launcher/gui/indicator/ProgressCircleIndicator.java
  Launcher/src/main/java/ru/gravit/launcher/gui/indicator/RingProgressIndicator.java
  Launcher/src/main/java/ru/gravit/launcher/gui/indicator/RingProgressIndicatorSkin.java
Labels: optimization

#52 Names, descriptions, submodifications and switch mechanics for additional mods
  Launcher/runtime/config.js
  Launcher/runtime/dialog/overlay/options/options.js
Labels: feature
